### ISSUE TITLE
We should add a note about kam only supports OpenShift

### ISSUE THREAD

**Issue by wtam2018** [redhat-developer/kam#31] opened 2020-09-25 16:01 UTC
### Is your task related to a problem? Please describe.

We should add a note about kam only supports OpenShift.  Users should be informed that kam currently only works in OCP.

### Describe the solution you'd like

We should add a note in the toplevel README.md.

### Describe alternatives you've considered

N/A
### Additional context

N/A

**Comment by bigkevmcd** [comment] 2020-09-28 10:27
This feels like a duplicate of https://github.com/redhat-developer/kam/issues/18

**Closed by bigkevmcd** 2020-09-28 10:27 UTC
